version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "My-ChatGPT-API"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-ik0i419utuv0"
s3_prefix = "ChatGPT_API"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
