AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  ChatGPT-API

  Sample SAM Template for ChatGPT-API
  
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 120

Resources:
  ChatGPTFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: hello-world/
      Handler: app.lambdaHandler
      Runtime: nodejs18.x
      Architectures:
        - x86_64
      Events:
        HelloWorld:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /ask
            Method: post
      Environment:
        Variables:
          OPENAI_API_KEY: put your Open AI API key

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  ChatGPTApi:
    Description: "API Gateway endpoint URL for Prod stage for Chat GPT function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/ask/"
  ChatGPTFunction:
    Description: "Chat GPT Lambda Function ARN"
    Value: !GetAtt ChatGPTFunction.Arn
  ChatGPTFunctionIamRole:
    Description: "Implicit IAM Role created for Chat GPT function"
    Value: !GetAtt ChatGPTFunctionRole.Arn
